name: lab_4_product_like
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets: 
  - assets/images/KMC-CSG-Matt.jpg
  - assets/images/KMC-Perfect-Hard-Size-Sleeve.jpg
  - assets/images/KMC-Side-in-Perfect-Size-Sleeve.jpg


